name: Tests

on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install build-essential libpoppler-cpp-dev pkg-config python-dev
      - name: Install pipenv
        run: pip install pipenv
      - name: Install development dependencies
        run: pipenv install --dev
      - name: Run tests
        run: pipenv run test
